<?php

namespace AppBundle\Repository;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportTransferRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSorted(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:AirportTransfer p ORDER BY p.weight DESC'
            )
            ->getResult();
    }
}
