<?php

namespace AppBundle\Repository;

/**
 * BlogentriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogentriesRepository extends \Doctrine\ORM\EntityRepository
{
}
