<?php

namespace AppBundle\Repository;

/**
 * BlogentrieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogentrieRepository extends \Doctrine\ORM\EntityRepository
{
}
