<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function listFutureBookings($page = 1, $count = 20)
    {

        return $this->createQueryBuilder("b")
            ->where("b.pickuptime >= :start_day")
            ->setParameter("start_day", new \DateTime('today'))
            ->orderBy("b.pickuptime", "ASC")
            ->setMaxResults($count)
            ->setFirstResult(($page - 1) * $count)

            ->getQuery()->getResult();
    }
    
    public function listBookings($page = 1, $count = 20)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Booking p ORDER BY p.pickuptime ASC'
            )

            ->setMaxResults($count)
            ->setFirstResult(($page - 1) * $count)
            ->getResult();
    }

    public function nextWeeksCount($week = 1)
    {

        return $this->createQueryBuilder("b")
                ->select("COUNT(b)")
                ->where("b.pickuptime >= :start_day")
                ->andWhere("b.pickuptime < :nextweek")
                ->setParameter("nextweek", new \DateTime("today + $week week"))
                ->setParameter("start_day", new \DateTime('today'))
                ->orderBy("b.id", "DESC")
                ->getQuery()
            ->getSingleScalarResult();
    }

}
