<?php

namespace AppBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function listBookings($page = 1, $count = 20)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Booking p ORDER BY p.id DESC'
            )

            ->setMaxResults($count)
            ->setFirstResult(($page - 1) * $count)
            ->getResult();
    }

    public function nextWeeksCount($week = 1)
    {

        return $this->createQueryBuilder("b")
                ->select("COUNT(b)")
                ->where("b.pickuptime > :yesterday")
                ->andWhere("b.pickuptime < :nextweek")
                ->setParameter("nextweek", new \DateTime("today + $week week"))
                ->setParameter("yesterday", new \DateTime('yesterday'))
                ->orderBy("b.id", "DESC")
                ->getQuery()
            ->getSingleScalarResult();
    }

}
