<?php

namespace AppBundle\Repository;

/**
 * ContactMsgsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMsgsRepository extends \Doctrine\ORM\EntityRepository
{
}
