<?php

namespace AppBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSorted(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Experience p ORDER BY p.weight DESC'
            )
            ->getResult();
    }
}
