<?php

namespace AppBundle\Repository;

/**
 * InfographItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfographItemRepository extends \Doctrine\ORM\EntityRepository
{
}
