<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNonePlaceNames()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.name FROM AppBundle:Place p'
            )
            ->getResult();
    }

    public function findAllSorted(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Place p ORDER BY p.weight DESC'
            )
            ->getResult();
    }
}
