<?php

namespace AppBundle\Repository;

/**
 * SocialnetworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialnetworkRepository extends \Doctrine\ORM\EntityRepository
{
}
