# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      chain_provider:
        chain:
          providers: [in_memory, db_provider]

      in_memory:
          memory:
            users:
              habanatechsupervisor:
                password: $2y$12$QqVqwXhk8JOpSa9WCeN4o.ia8y7PaXikgKbUwmwiG8IT3oi5i8vu2
                roles: ['ROLE_USER', 'ROLE_ADMIN', 'ROLE_SUPERVISOR']

      db_provider:
          entity:
            class: AppBundle:User
            property: username        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /dash
                failure_path: home
              #  csrf_provider: security.csrf.token_manager
            logout:
                path: logout
                target: /
            logout_on_user_change: true
            provider: chain_provider


            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      # require ROLE_ADMIN for /admin
     # - { path: ^/dash/supervisor, roles: ROLE_SUPERVISOR }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/dash, roles: ROLE_ADMIN } # , requires_channel: https } #TODO: set requires_channel:https
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https }

     

    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt

        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12